# Generated by Django 5.1.3 on 2025-05-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_dependencies_task_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='component',
        ),
    ]
