# Generated by Django 5.1.3 on 2025-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_image_category_delete_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [models.OrderBy(models.F('priority'), nulls_last=True)], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
